global:
  scrape_interval: 1s
  evaluation_interval: 1s

  external_labels:
    monitor: 'blts'

scrape_configs:
  - job_name: 's'
    static_configs:
      - targets: ['localhost:8000','localhost:8001','localhost:8002','localhost:8003','localhost:8004','localhost:8005','localhost:8006','localhost:8007','localhost:8008','localhost:8009']
  - job_name: 'lb'
    static_configs:
      - targets: ['localhost:9001']

rule_files:
  - 'task.rules'
  - 'errors.rules'
  - 'latency.rules'
  - 'slo.rules.yml'
